// client/src/components/PolicyInputForm.tsx
import { useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Home, Shield, AlertCircle } from "lucide-react";

interface PolicyData {
  propertyAddress: string;
  propertyType: string;
  constructionYear: string;
  squareFootage: string;
  replacementCost: string;
  dwellingCoverage: string;
  personalPropertyCoverage: string;
  liabilityCoverage: string;
  deductible: string;
  lossOfUseCoverage: string;
  hasFloodCoverage: boolean;
  hasEarthquakeCoverage: boolean;
  claimsLast5Years: string;
  hasMortgage: boolean;
}

interface PolicyInputFormProps {
  onAnalyze: (data: PolicyData) => void;
}

export default function PolicyInputForm({ onAnalyze }: PolicyInputFormProps) {
  const [formData, setFormData] = useState<PolicyData>({
    propertyAddress: "",
    propertyType: "",
    constructionYear: "",
    squareFootage: "",
    replacementCost: "",
    dwellingCoverage: "",
    personalPropertyCoverage: "",
    liabilityCoverage: "",
    deductible: "",
    lossOfUseCoverage: "",
    hasFloodCoverage: false,
    hasEarthquakeCoverage: false,
    claimsLast5Years: "",
    hasMortgage: false,
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    console.log("Analyzing coverage with data:", formData);
    onAnalyze(formData);
  };

  const updateField = (field: keyof PolicyData, value: string | boolean) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  return (
    <Card className="w-full">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Home className="h-5 w-5" />
          Policy Information
        </CardTitle>
        <CardDescription>
          Enter your current policy details to analyze coverage gaps
        </CardDescription>
      </CardHeader>
      <CardContent>
        <form onSubmit={handleSubmit} className="space-y-6">
          <Accordion type="multiple" defaultValue={["property", "coverage"]} className="w-full">
            <AccordionItem value="property" data-testid="accordion-property">
              <AccordionTrigger className="text-base font-semibold">
                Property Information
              </AccordionTrigger>
              <AccordionContent className="space-y-4 pt-4">
                <div className="space-y-2">
                  <Label htmlFor="propertyAddress">Property Address</Label>
                  <Input
                    id="propertyAddress"
                    data-testid="input-property-address"
                    placeholder="123 Main St, City, State ZIP"
                    value={formData.propertyAddress}
                    onChange={(e) => updateField("propertyAddress", e.target.value)}
                  />
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="propertyType">Property Type</Label>
                    <Select
                      value={formData.propertyType}
                      onValueChange={(value) => updateField("propertyType", value)}
                    >
                      <SelectTrigger id="propertyType" data-testid="select-property-type">
                        <SelectValue placeholder="Select type" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="single-family">Single Family Home</SelectItem>
                        <SelectItem value="condo">Condominium</SelectItem>
                        <SelectItem value="townhouse">Townhouse</SelectItem>
                        <SelectItem value="rental">Rental Property</SelectItem>
                        <SelectItem value="multi-family">Multi-Family</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="constructionYear">Construction Year</Label>
                    <Input
                      id="constructionYear"
                      data-testid="input-construction-year"
                      type="number"
                      placeholder="2000"
                      value={formData.constructionYear}
                      onChange={(e) => updateField("constructionYear", e.target.value)}
                    />
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="squareFootage">Square Footage</Label>
                    <Input
                      id="squareFootage"
                      data-testid="input-square-footage"
                      type="number"
                      placeholder="2000"
                      value={formData.squareFootage}
                      onChange={(e) => updateField("squareFootage", e.target.value)}
                    />
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="replacementCost">Estimated Replacement Cost</Label>
                    <Input
                      id="replacementCost"
                      data-testid="input-replacement-cost"
                      type="number"
                      placeholder="500000"
                      value={formData.replacementCost}
                      onChange={(e) => updateField("replacementCost", e.target.value)}
                    />
                  </div>
                </div>
              </AccordionContent>
            </AccordionItem>

            <AccordionItem value="coverage" data-testid="accordion-coverage">
              <AccordionTrigger className="text-base font-semibold">
                Current Coverage Details
              </AccordionTrigger>
              <AccordionContent className="space-y-4 pt-4">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="dwellingCoverage">Dwelling Coverage (Coverage A)</Label>
                    <Input
                      id="dwellingCoverage"
                      data-testid="input-dwelling-coverage"
                      type="number"
                      placeholder="400000"
                      value={formData.dwellingCoverage}
                      onChange={(e) => updateField("dwellingCoverage", e.target.value)}
                    />
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="personalPropertyCoverage">Personal Property (Coverage C)</Label>
                    <Input
                      id="personalPropertyCoverage"
                      data-testid="input-personal-property"
                      type="number"
                      placeholder="200000"
                      value={formData.personalPropertyCoverage}
                      onChange={(e) => updateField("personalPropertyCoverage", e.target.value)}
                    />
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="liabilityCoverage">Liability Limit (Coverage E)</Label>
                    <Select
                      value={formData.liabilityCoverage}
                      onValueChange={(value) => updateField("liabilityCoverage", value)}
                    >
                      <SelectTrigger id="liabilityCoverage" data-testid="select-liability">
                        <SelectValue placeholder="Select amount" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="100000">$100,000</SelectItem>
                        <SelectItem value="300000">$300,000</SelectItem>
                        <SelectItem value="500000">$500,000</SelectItem>
                        <SelectItem value="1000000">$1,000,000</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="deductible">Deductible</Label>
                    <Select
                      value={formData.deductible}
                      onValueChange={(value) => updateField("deductible", value)}
                    >
                      <SelectTrigger id="deductible" data-testid="select-deductible">
                        <SelectValue placeholder="Select amount" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="500">$500</SelectItem>
                        <SelectItem value="1000">$1,000</SelectItem>
                        <SelectItem value="2500">$2,500</SelectItem>
                        <SelectItem value="5000">$5,000</SelectItem>
                        <SelectItem value="10000">$10,000</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="lossOfUseCoverage">Loss of Use / ALE (Coverage D)</Label>
                  <Input
                    id="lossOfUseCoverage"
                    data-testid="input-loss-of-use"
                    type="number"
                    placeholder="80000"
                    value={formData.lossOfUseCoverage}
                    onChange={(e) => updateField("lossOfUseCoverage", e.target.value)}
                  />
                </div>

                <div className="space-y-4 pt-2">
                  <div className="flex items-center justify-between">
                    <div className="space-y-0.5">
                      <Label htmlFor="floodCoverage">Flood Insurance</Label>
                      <p className="text-sm text-muted-foreground">Separate policy coverage</p>
                    </div>
                    <Switch
                      id="floodCoverage"
                      data-testid="switch-flood"
                      checked={formData.hasFloodCoverage}
                      onCheckedChange={(checked) => updateField("hasFloodCoverage", checked)}
                    />
                  </div>

                  <div className="flex items-center justify-between">
                    <div className="space-y-0.5">
                      <Label htmlFor="earthquakeCoverage">Earthquake Insurance</Label>
                      <p className="text-sm text-muted-foreground">Additional coverage rider</p>
                    </div>
                    <Switch
                      id="earthquakeCoverage"
                      data-testid="switch-earthquake"
                      checked={formData.hasEarthquakeCoverage}
                      onCheckedChange={(checked) => updateField("hasEarthquakeCoverage", checked)}
                    />
                  </div>
                </div>
              </AccordionContent>
            </AccordionItem>

            <AccordionItem value="additional" data-testid="accordion-additional">
              <AccordionTrigger className="text-base font-semibold">
                Additional Information
              </AccordionTrigger>
              <AccordionContent className="space-y-4 pt-4">
                <div className="space-y-2">
                  <Label htmlFor="claimsLast5Years">Number of Claims (Last 5 Years)</Label>
                  <Input
                    id="claimsLast5Years"
                    data-testid="input-claims"
                    type="number"
                    placeholder="0"
                    min="0"
                    value={formData.claimsLast5Years}
                    onChange={(e) => updateField("claimsLast5Years", e.target.value)}
                  />
                </div>

                <div className="flex items-center justify-between">
                  <div className="space-y-0.5">
                    <Label htmlFor="mortgage">Active Mortgage or Lien</Label>
                    <p className="text-sm text-muted-foreground">Lender requirements may apply</p>
                  </div>
                  <Switch
                    id="mortgage"
                    data-testid="switch-mortgage"
                    checked={formData.hasMortgage}
                    onCheckedChange={(checked) => updateField("hasMortgage", checked)}
                  />
                </div>
              </AccordionContent>
            </AccordionItem>
          </Accordion>

          <Button 
            type="submit" 
            className="w-full" 
            size="lg"
            data-testid="button-analyze"
          >
            <Shield className="mr-2 h-4 w-4" />
            Analyze Coverage
          </Button>
        </form>
      </CardContent>
    </Card>
  );
}

// client/src/app/components/policy-input-form/policy-input-form.component.ts
import { Component, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatSlideToggleModule } from '@angular/material/slide-toggle';
import { MatButtonModule } from '@angular/material/button';
import { MatExpansionModule } from '@angular/material/expansion';
import { MatIconModule } from '@angular/material/icon';
import { PolicyData } from '../../services/policy-analysis.service';

@Component({
  selector: 'app-policy-input-form',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatSlideToggleModule,
    MatButtonModule,
    MatExpansionModule,
    MatIconModule
  ],
  templateUrl: './policy-input-form.component.html'
})
export class PolicyInputFormComponent {
  @Output() analyze = new EventEmitter<PolicyData>();

  policyForm: FormGroup;

  constructor(private fb: FormBuilder) {
    this.policyForm = this.fb.group({
      propertyAddress: ['', Validators.required],
      propertyType: ['', Validators.required],
      constructionYear: ['', [Validators.required, Validators.min(1800)]],
      squareFootage: ['', [Validators.required, Validators.min(1)]],
      replacementCost: ['', [Validators.required, Validators.min(1)]],
      dwellingCoverage: ['', [Validators.required, Validators.min(1)]],
      personalPropertyCoverage: ['', [Validators.required, Validators.min(0)]],
      liabilityCoverage: ['', Validators.required],
      deductible: ['', Validators.required],
      lossOfUseCoverage: ['', [Validators.required, Validators.min(0)]],
      hasFloodCoverage: [false],
      hasEarthquakeCoverage: [false],
      claimsLast5Years: ['0', [Validators.required, Validators.min(0)]],
      hasMortgage: [false]
    });
  }

  onSubmit(): void {
    if (this.policyForm.valid) {
      this.analyze.emit(this.policyForm.value as PolicyData);
    }
  }
}

<mat-card class="w-full">
  <mat-card-header>
    <mat-card-title class="flex items-center gap-2">
      <mat-icon>home</mat-icon>
      Policy Information
    </mat-card-title>
    <mat-card-subtitle>
      Enter your current policy details to analyze coverage gaps
    </mat-card-subtitle>
  </mat-card-header>
  
  <mat-card-content>
    <form [formGroup]="policyForm" (ngSubmit)="onSubmit()" class="space-y-6">
      <mat-accordion multi>
        <mat-expansion-panel [expanded]="true" data-testid="accordion-property">
          <mat-expansion-panel-header>
            <mat-panel-title class="text-base font-semibold">
              Property Information
            </mat-panel-title>
          </mat-expansion-panel-header>

          <div class="space-y-4 pt-4">
            <mat-form-field class="w-full" appearance="outline">
              <mat-label>Property Address</mat-label>
              <input matInput formControlName="propertyAddress" 
                     placeholder="123 Main St, City, State ZIP"
                     data-testid="input-property-address">
            </mat-form-field>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
              <mat-form-field appearance="outline">
                <mat-label>Property Type</mat-label>
                <mat-select formControlName="propertyType" data-testid="select-property-type">
                  <mat-option value="single-family">Single Family Home</mat-option>
                  <mat-option value="condo">Condominium</mat-option>
                  <mat-option value="townhouse">Townhouse</mat-option>
                  <mat-option value="rental">Rental Property</mat-option>
                  <mat-option value="multi-family">Multi-Family</mat-option>
                </mat-select>
              </mat-form-field>

              <mat-form-field appearance="outline">
                <mat-label>Construction Year</mat-label>
                <input matInput type="number" formControlName="constructionYear" 
                       placeholder="2000"
                       data-testid="input-construction-year">
              </mat-form-field>
            </div>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
              <mat-form-field appearance="outline">
                <mat-label>Square Footage</mat-label>
                <input matInput type="number" formControlName="squareFootage" 
                       placeholder="2000"
                       data-testid="input-square-footage">
              </mat-form-field>

              <mat-form-field appearance="outline">
                <mat-label>Estimated Replacement Cost</mat-label>
                <input matInput type="number" formControlName="replacementCost" 
                       placeholder="500000"
                       data-testid="input-replacement-cost">
              </mat-form-field>
            </div>
          </div>
        </mat-expansion-panel>

        <mat-expansion-panel [expanded]="true" data-testid="accordion-coverage">
          <mat-expansion-panel-header>
            <mat-panel-title class="text-base font-semibold">
              Current Coverage Details
            </mat-panel-title>
          </mat-expansion-panel-header>

          <div class="space-y-4 pt-4">
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
              <mat-form-field appearance="outline">
                <mat-label>Dwelling Coverage (Coverage A)</mat-label>
                <input matInput type="number" formControlName="dwellingCoverage" 
                       placeholder="400000"
                       data-testid="input-dwelling-coverage">
              </mat-form-field>

              <mat-form-field appearance="outline">
                <mat-label>Personal Property (Coverage C)</mat-label>
                <input matInput type="number" formControlName="personalPropertyCoverage" 
                       placeholder="200000"
                       data-testid="input-personal-property">
              </mat-form-field>
            </div>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
              <mat-form-field appearance="outline">
                <mat-label>Liability Limit (Coverage E)</mat-label>
                <mat-select formControlName="liabilityCoverage" data-testid="select-liability">
                  <mat-option value="100000">$100,000</mat-option>
                  <mat-option value="300000">$300,000</mat-option>
                  <mat-option value="500000">$500,000</mat-option>
                  <mat-option value="1000000">$1,000,000</mat-option>
                </mat-select>
              </mat-form-field>

              <mat-form-field appearance="outline">
                <mat-label>Deductible</mat-label>
                <mat-select formControlName="deductible" data-testid="select-deductible">
                  <mat-option value="500">$500</mat-option>
                  <mat-option value="1000">$1,000</mat-option>
                  <mat-option value="2500">$2,500</mat-option>
                  <mat-option value="5000">$5,000</mat-option>
                  <mat-option value="10000">$10,000</mat-option>
                </mat-select>
              </mat-form-field>
            </div>

            <mat-form-field class="w-full" appearance="outline">
              <mat-label>Loss of Use / ALE (Coverage D)</mat-label>
              <input matInput type="number" formControlName="lossOfUseCoverage" 
                     placeholder="80000"
                     data-testid="input-loss-of-use">
            </mat-form-field>

            <div class="space-y-4 pt-2">
              <div class="flex items-center justify-between">
                <div>
                  <div class="font-medium">Flood Insurance</div>
                  <div class="text-sm text-muted-foreground">Separate policy coverage</div>
                </div>
                <mat-slide-toggle formControlName="hasFloodCoverage" data-testid="switch-flood">
                </mat-slide-toggle>
              </div>

              <div class="flex items-center justify-between">
                <div>
                  <div class="font-medium">Earthquake Insurance</div>
                  <div class="text-sm text-muted-foreground">Additional coverage rider</div>
                </div>
                <mat-slide-toggle formControlName="hasEarthquakeCoverage" data-testid="switch-earthquake">
                </mat-slide-toggle>
              </div>
            </div>
          </div>
        </mat-expansion-panel>

        <mat-expansion-panel data-testid="accordion-additional">
          <mat-expansion-panel-header>
            <mat-panel-title class="text-base font-semibold">
              Additional Information
            </mat-panel-title>
          </mat-expansion-panel-header>

          <div class="space-y-4 pt-4">
            <mat-form-field class="w-full" appearance="outline">
              <mat-label>Number of Claims (Last 5 Years)</mat-label>
              <input matInput type="number" formControlName="claimsLast5Years" 
                     placeholder="0" min="0"
                     data-testid="input-claims">
            </mat-form-field>

            <div class="flex items-center justify-between">
              <div>
                <div class="font-medium">Active Mortgage or Lien</div>
                <div class="text-sm text-muted-foreground">Lender requirements may apply</div>
              </div>
              <mat-slide-toggle formControlName="hasMortgage" data-testid="switch-mortgage">
              </mat-slide-toggle>
            </div>
          </div>
        </mat-expansion-panel>
      </mat-accordion>

      <button mat-raised-button color="primary" type="submit" 
              class="w-full" 
              [disabled]="!policyForm.valid"
              data-testid="button-analyze">
        <mat-icon>shield</mat-icon>
        Analyze Coverage
      </button>
    </form>
  </mat-card-content>
</mat-card>
