// client/src/components/ComparisonBar.tsx
interface ComparisonBarProps {
  label: string;
  currentAmount: number;
  recommendedAmount: number;
  maxAmount?: number;
}

export default function ComparisonBar({
  label,
  currentAmount,
  recommendedAmount,
  maxAmount,
}: ComparisonBarProps) {
  const max = maxAmount || Math.max(currentAmount, recommendedAmount) * 1.2;
  const currentPercentage = (currentAmount / max) * 100;
  const recommendedPercentage = (recommendedAmount / max) * 100;
  const isSufficient = currentAmount >= recommendedAmount;

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat("en-US", {
      style: "currency",
      currency: "USD",
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(amount);
  };

  return (
    <div className="space-y-2" data-testid={`comparison-${label.toLowerCase().replace(/\s+/g, '-')}`}>
      <div className="flex justify-between items-baseline">
        <span className="text-sm font-medium">{label}</span>
        <span className="text-sm text-muted-foreground">
          {isSufficient ? "✓ Adequate" : "Gap Identified"}
        </span>
      </div>

      <div className="space-y-2">
        <div className="flex items-center gap-2">
          <span className="text-xs text-muted-foreground w-20">Current</span>
          <div className="flex-1 bg-muted rounded-full h-6 relative overflow-hidden">
            <div
              className={`h-full rounded-full ${
                isSufficient ? "bg-success" : "bg-warning"
              } transition-all duration-500 flex items-center justify-end pr-2`}
              style={{ width: `${Math.min(currentPercentage, 100)}%` }}
            >
              {currentPercentage > 20 && (
                <span className="text-xs font-medium text-white">
                  {formatCurrency(currentAmount)}
                </span>
              )}
            </div>
          </div>
          {currentPercentage <= 20 && (
            <span className="text-xs font-medium w-24 text-right">
              {formatCurrency(currentAmount)}
            </span>
          )}
        </div>

        <div className="flex items-center gap-2">
          <span className="text-xs text-muted-foreground w-20">Target</span>
          <div className="flex-1 bg-muted rounded-full h-6 relative overflow-hidden">
            <div
              className="h-full bg-primary rounded-full transition-all duration-500 flex items-center justify-end pr-2"
              style={{ width: `${Math.min(recommendedPercentage, 100)}%` }}
            >
              {recommendedPercentage > 20 && (
                <span className="text-xs font-medium text-primary-foreground">
                  {formatCurrency(recommendedAmount)}
                </span>
              )}
            </div>
          </div>
          {recommendedPercentage <= 20 && (
            <span className="text-xs font-medium w-24 text-right">
              {formatCurrency(recommendedAmount)}
            </span>
          )}
        </div>
      </div>
    </div>
  );
}

// client/src/app/components/comparison-bar/comparison-bar.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-comparison-bar',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="space-y-2" [attr.data-testid]="getTestId()">
      <div class="flex justify-between items-baseline">
        <span class="text-sm font-medium">{{ label }}</span>
        <span class="text-sm text-muted-foreground">
          {{ isSufficient() ? '✓ Adequate' : 'Gap Identified' }}
        </span>
      </div>

      <div class="space-y-2">
        <div class="flex items-center gap-2">
          <span class="text-xs text-muted-foreground w-20">Current</span>
          <div class="flex-1 bg-muted rounded-full h-6 relative overflow-hidden">
            <div
              class="h-full rounded-full transition-all duration-500 flex items-center justify-end pr-2"
              [ngClass]="isSufficient() ? 'bg-success' : 'bg-warning'"
              [style.width.%]="Math.min(getCurrentPercentage(), 100)">
              <span *ngIf="getCurrentPercentage() > 20" class="text-xs font-medium text-white">
                {{ currentAmount | currency:'USD':'symbol':'1.0-0' }}
              </span>
            </div>
          </div>
          <span *ngIf="getCurrentPercentage() <= 20" class="text-xs font-medium w-24 text-right">
            {{ currentAmount | currency:'USD':'symbol':'1.0-0' }}
          </span>
        </div>

        <div class="flex items-center gap-2">
          <span class="text-xs text-muted-foreground w-20">Target</span>
          <div class="flex-1 bg-muted rounded-full h-6 relative overflow-hidden">
            <div
              class="h-full bg-primary rounded-full transition-all duration-500 flex items-center justify-end pr-2"
              [style.width.%]="Math.min(getRecommendedPercentage(), 100)">
              <span *ngIf="getRecommendedPercentage() > 20" class="text-xs font-medium text-primary-foreground">
                {{ recommendedAmount | currency:'USD':'symbol':'1.0-0' }}
              </span>
            </div>
          </div>
          <span *ngIf="getRecommendedPercentage() <= 20" class="text-xs font-medium w-24 text-right">
            {{ recommendedAmount | currency:'USD':'symbol':'1.0-0' }}
          </span>
        </div>
      </div>
    </div>
  `
})
export class ComparisonBarComponent {
  @Input() label!: string;
  @Input() currentAmount!: number;
  @Input() recommendedAmount!: number;
  @Input() maxAmount?: number;

  Math = Math;

  getMaxAmount(): number {
    return this.maxAmount || Math.max(this.currentAmount, this.recommendedAmount) * 1.2;
  }

  getCurrentPercentage(): number {
    return (this.currentAmount / this.getMaxAmount()) * 100;
  }

  getRecommendedPercentage(): number {
    return (this.recommendedAmount / this.getMaxAmount()) * 100;
  }

  isSufficient(): boolean {
    return this.currentAmount >= this.recommendedAmount;
  }

  getTestId(): string {
    return 'comparison-' + this.label.toLowerCase().replace(/\s+/g, '-');
  }
}
