// client/src/components/AppHeader.tsx
import { Shield, Moon, Sun } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useState, useEffect } from "react";

export default function AppHeader() {
  const [isDark, setIsDark] = useState(false);

  useEffect(() => {
    const root = document.documentElement;
    const isDarkMode = root.classList.contains("dark");
    setIsDark(isDarkMode);
  }, []);

  const toggleTheme = () => {
    const root = document.documentElement;
    const newIsDark = !isDark;
    
    if (newIsDark) {
      root.classList.add("dark");
    } else {
      root.classList.remove("dark");
    }
    
    setIsDark(newIsDark);
    localStorage.setItem("theme", newIsDark ? "dark" : "light");
    console.log("Theme toggled to:", newIsDark ? "dark" : "light");
  };

  return (
    <header className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
      <div className="container mx-auto flex h-16 items-center justify-between px-4">
        <div className="flex items-center gap-3">
          <div className="flex items-center justify-center w-10 h-10 rounded-md bg-primary text-primary-foreground">
            <Shield className="h-6 w-6" />
          </div>
          <div>
            <h1 className="text-xl font-semibold" data-testid="text-app-title">
              Coverage Gap Analyzer
            </h1>
            <p className="text-xs text-muted-foreground hidden sm:block">
              P&C Insurance Assessment Tool
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            size="default"
            data-testid="button-new-analysis"
            onClick={() => {
              console.log("Starting new analysis...");
              window.location.reload();
            }}
          >
            New Analysis
          </Button>
          <Button
            variant="ghost"
            size="icon"
            onClick={toggleTheme}
            data-testid="button-theme-toggle"
          >
            {isDark ? <Sun className="h-5 w-5" /> : <Moon className="h-5 w-5" />}
          </Button>
        </div>
      </div>
    </header>
  );
}

// client/src/app/components/app-header/app-header.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatToolbarModule } from '@angular/material/toolbar';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { ThemeService } from '../../services/theme.service';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [CommonModule, MatToolbarModule, MatButtonModule, MatIconModule],
  template: `
    <header class="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur">
      <div class="container mx-auto flex h-16 items-center justify-between px-4">
        <div class="flex items-center gap-3">
          <div class="flex items-center justify-center w-10 h-10 rounded-md bg-primary text-primary-foreground">
            <mat-icon>shield</mat-icon>
          </div>
          <div>
            <h1 class="text-xl font-semibold" data-testid="text-app-title">
              Coverage Gap Analyzer
            </h1>
            <p class="text-xs text-muted-foreground hidden sm:block">
              P&C Insurance Assessment Tool
            </p>
          </div>
        </div>

        <div class="flex items-center gap-2">
          <button 
            mat-stroked-button
            data-testid="button-new-analysis"
            (click)="newAnalysis()">
            New Analysis
          </button>
          <button 
            mat-icon-button
            data-testid="button-theme-toggle"
            (click)="toggleTheme()">
            <mat-icon>{{ (isDarkMode$ | async) ? 'light_mode' : 'dark_mode' }}</mat-icon>
          </button>
        </div>
      </div>
    </header>
  `
})
export class AppHeaderComponent {
  isDarkMode$ = this.themeService.isDarkMode$;

  constructor(private themeService: ThemeService) {}

  toggleTheme(): void {
    this.themeService.toggleTheme();
  }

  newAnalysis(): void {
    window.location.reload();
  }
}
