// client/src/components/CoverageGauge.tsx
import { AlertTriangle, CheckCircle2, XCircle } from "lucide-react";

interface CoverageGaugeProps {
  percentage: number;
  size?: "sm" | "md" | "lg";
}

export default function CoverageGauge({ percentage, size = "md" }: CoverageGaugeProps) {
  const getStatus = () => {
    if (percentage >= 80) return { color: "text-success", bgColor: "text-success", icon: CheckCircle2, label: "Adequate" };
    if (percentage >= 50) return { color: "text-warning", bgColor: "text-warning", icon: AlertTriangle, label: "Moderate Risk" };
    return { color: "text-destructive", bgColor: "text-destructive", icon: XCircle, label: "Critical Gaps" };
  };

  const status = getStatus();
  const Icon = status.icon;

  const sizes = {
    sm: { container: "w-24 h-24", text: "text-lg", icon: "h-4 w-4", stroke: 6 },
    md: { container: "w-32 h-32", text: "text-2xl", icon: "h-5 w-5", stroke: 8 },
    lg: { container: "w-40 h-40", text: "text-3xl", icon: "h-6 w-6", stroke: 10 },
  };

  const config = sizes[size];
  const radius = 50 - config.stroke / 2;
  const circumference = 2 * Math.PI * radius;
  const offset = circumference - (percentage / 100) * circumference;

  return (
    <div className="flex flex-col items-center gap-4">
      <div className={`relative ${config.container}`}>
        <svg className="transform -rotate-90 w-full h-full" data-testid="gauge-svg">
          <circle
            cx="50%"
            cy="50%"
            r={radius}
            stroke="currentColor"
            strokeWidth={config.stroke}
            fill="none"
            className="text-muted"
          />
          <circle
            cx="50%"
            cy="50%"
            r={radius}
            stroke="currentColor"
            strokeWidth={config.stroke}
            fill="none"
            strokeDasharray={circumference}
            strokeDashoffset={offset}
            strokeLinecap="round"
            className={`${status.bgColor} transition-all duration-1000`}
          />
        </svg>
        <div className="absolute inset-0 flex items-center justify-center">
          <span className={`${config.text} font-semibold ${status.color}`} data-testid="gauge-percentage">
            {percentage}%
          </span>
        </div>
      </div>
      <div className={`flex items-center gap-2 ${status.color}`}>
        <Icon className={config.icon} />
        <span className="font-medium" data-testid="gauge-status">{status.label}</span>
      </div>
    </div>
  );
}

// client/src/app/components/coverage-gauge/coverage-gauge.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatIconModule } from '@angular/material/icon';

@Component({
  selector: 'app-coverage-gauge',
  standalone: true,
  imports: [CommonModule, MatIconModule],
  template: `
    <div class="flex flex-col items-center gap-4">
      <div [ngClass]="getSizeClass()">
        <svg class="transform -rotate-90 w-full h-full" data-testid="gauge-svg">
          <circle
            cx="50%"
            cy="50%"
            [attr.r]="radius"
            stroke="currentColor"
            [attr.stroke-width]="strokeWidth"
            fill="none"
            class="text-muted"
          />
          <circle
            cx="50%"
            cy="50%"
            [attr.r]="radius"
            stroke="currentColor"
            [attr.stroke-width]="strokeWidth"
            fill="none"
            [attr.stroke-dasharray]="circumference"
            [attr.stroke-dashoffset]="offset"
            stroke-linecap="round"
            [ngClass]="getStatusColor()"
            class="transition-all duration-1000"
          />
        </svg>
        <div class="absolute inset-0 flex items-center justify-center">
          <span [ngClass]="[getTextSize(), getStatusColor()]" class="font-semibold" data-testid="gauge-percentage">
            {{ percentage }}%
          </span>
        </div>
      </div>
      <div class="flex items-center gap-2" [ngClass]="getStatusColor()">
        <mat-icon [ngClass]="getIconSize()">{{ getStatusIcon() }}</mat-icon>
        <span class="font-medium" data-testid="gauge-status">{{ getStatusLabel() }}</span>
      </div>
    </div>
  `
})
export class CoverageGaugeComponent {
  @Input() percentage!: number;
  @Input() size: 'sm' | 'md' | 'lg' = 'md';

  get radius(): number {
    const strokeWidths = { sm: 6, md: 8, lg: 10 };
    return 50 - strokeWidths[this.size] / 2;
  }

  get strokeWidth(): number {
    const strokeWidths = { sm: 6, md: 8, lg: 10 };
    return strokeWidths[this.size];
  }

  get circumference(): number {
    return 2 * Math.PI * this.radius;
  }

  get offset(): number {
    return this.circumference - (this.percentage / 100) * this.circumference;
  }

  getSizeClass(): string {
    const classes = {
      sm: 'relative w-24 h-24',
      md: 'relative w-32 h-32',
      lg: 'relative w-40 h-40'
    };
    return classes[this.size];
  }

  getTextSize(): string {
    const classes = {
      sm: 'text-lg',
      md: 'text-2xl',
      lg: 'text-3xl'
    };
    return classes[this.size];
  }

  getIconSize(): string {
    const classes = {
      sm: 'text-base',
      md: 'text-xl',
      lg: 'text-2xl'
    };
    return classes[this.size];
  }

  getStatusColor(): string {
    if (this.percentage >= 80) return 'text-success';
    if (this.percentage >= 50) return 'text-warning';
    return 'text-destructive';
  }

  getStatusLabel(): string {
    if (this.percentage >= 80) return 'Adequate';
    if (this.percentage >= 50) return 'Moderate Risk';
    return 'Critical Gaps';
  }

  getStatusIcon(): string {
    if (this.percentage >= 80) return 'check_circle';
    if (this.percentage >= 50) return 'warning';
    return 'cancel';
  }
}
